import type { NextPage } from 'next'
import Head from 'next/head'
import MainLayout from '../layouts/MainLayout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Музыкальная площадка</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <h1 style={{ margin: 0 }}>Добро пожаловать</h1>
        <h3>Здесь собраны самые лучшие треки мира!</h3>
      </MainLayout>
    </>
  )
}

export default Home
